### ISSUE TITLE
remove fixed module header

### ISSUE THREAD

**Issue by vwegert** [hggh/MMM-OpenHAB-Items#1]
The module header can usually be configured for every module:
```
		{
			module: "MMM-OpenHAB-Items",
			position: "top_right",
			header: "OpenHAB,"
			config: {
				// ...
			],
			}
		},
```
With the current implementation, this is not possible - it's also not possible to omit the header to save space. I'd suggest removing the hard-coded header entirely.

**Comment by hggh** [comment]
fixed with https://github.com/hggh/MMM-OpenHAB-Items/pull/2
